#!/usr/bin/python

import os.path as path
import imp

cxxtest_path = '../../../cxxtest/'
cxxtestbuilder_path = path.join(cxxtest_path, 'build_tools/SCons/cxxtest.py')

cxxtest = imp.load_source('cxxtest', cxxtestbuilder_path)

env = Environment()

cxxtest.generate(env, CXXTEST_INSTALL_DIR = cxxtest_path)

src_files = []
blocks = [ '../blocks/SWE_DimensionalSplitting.cpp', '../blocks/SWE_Block.cpp' ]
swe1d  = [ 'SWE1D/WavePropagation.cpp' ]
src_files.extend(blocks)
src_files.extend(swe1d)

env.CxxTest('test_dimsplit', ['DimensionalSplittingTest.t.h', src_files], CPPPATH='..')

